image: python:3.7

test:
  stage: test
  script:
  - pip install -U -r docs/requirements.txt
  - sphinx-build -b html docs public
  only:
  - branches
  except:
  - master
  artifacts:
    expire_in: '10'
    when: always

pages:
  stage: deploy
  script:
  - pip install -U -r docs/requirements.txt
  - sphinx-build -b html docs public
  artifacts:
    expire_in: '10'
    when: always
    paths:
    - public
  only:
  - master

    
