
##########################
# Customize installation #
##########################

# For a minimal installation, just comment all,
# none of these option is necessary

# IINSTALL_SUBCOMMANDS (update, add-event) : permit to edit config files
# INSTALL_ADDONS : scripts to be linked to button in calendar 
# INSTALL_ALL_THEMES : if commented install only default theme
# INSTALL_MANPAGE : -
# iNSTALL_BASH_COMPLETION : see COMPLETION_PATH, default conf for debian

INSTALL_SUBCOMMANDS := True
INSTALL_ADDONS := True
INSTALL_ALL_THEMES := True
INSTALL_MANPAGE := True
INSTALL_BASH_COMPLETION := True


#######################
# Installation prefix #
#######################

# set installation prefix (default = /usr/local)
# prefer "$HOME/.local" for local install
#
# Recommanded values (debian):
#
# 	- /usr (root)
# 	- $HOME/.local (user)
#
PREFIX := $(HOME)/.local


# set completion path (default = $(prefix)/share/bash-completion/completions)
#COMPLETION_PATH := /usr/share/bash-completion/completions
