##########################
# Customize installation #
##########################
# Customize manual installation during "make install"
# (options are ignored when building debian package)

# Modules description :
# SUBCOMMANDS (update, add-event) : permit to edit config files
# ADDONS : scripts to be linked to button in calendar
# EVENTS : configuration file for events, if not use default hardcoded folder
# THEMES : install all themes or only default one
# MANPAGE : -
# BASH_COMPLETION : see COMPLETION_PATH, default conf for debian

# For a minimal installation, just comment all,
# none of these option is necessary

INSTALL_SUBCOMMANDS := True
INSTALL_ADDONS := True
INSTALL_EVENTS := True
INSTALL_ALL_THEMES := True
INSTALL_MANPAGE := True
INSTALL_BASH_COMPLETION := True
