
##########################
# Customize installation #
##########################

# For a minimal installation, just comment all
INSTALL_SUBCOMMANDS := True
INSTALL_ADDONS := True
INSTALL_ALL_THEMES := True
INSTALL_MANPAGE := True 
INSTALL_BASH_COMPLETION := True

#######################
# Installation prefix #
#######################

# set installation prefix (default = /usr/local)
# prefer "$HOME/.local" for local install
PREFIX := $(HOME)/.local

# set completion path (default = $(prefix)/share/bash-completion/completions)
#COMPLETION_PATH := /usr/share/bash-completion/completions
