#!/usr/bin/env bash


if [[ $1 =~ ^(update|add-event)$ ]]; then

    action=$1
    shift # skip subcommand

    if [[ $action == "update" ]]; then
        #/usr/share/naivecalendar/naivecalendar-update-all-themes "$@"

        /usr/share/naivecalendar/tools/naivecalendar-update "$@"

    elif [[ $action == "add-event" ]]; then
        /usr/share/naivecalendar/tools/naivecalendar-add-event "$@"

    fi

else 

    /usr/share/naivecalendar/naivecalendar.sh "$@"

fi
