.TH NAIVECALENDAR 1 "January 6, 2021"

.SH NAME
naivecalendar-configure
- Easily clone or edit configuration files

**arguments:**
  -h, --help                show this help message and exit
  -c TYPE, --clone TYPE     
  -e TYPE, --edit TYPE      

.SH SYNOPSIS
.B naivecalendar-configure [-h] [-c|-e
.I TYPE
.B ]

.SH DESCRIPTION
.B naivecalendar-configure
is an asset to easily clone or open configuration files (SCRIPTS, THEMES, EVENTS)

.SH OPTIONS

.TP
.B -h|--help 
show this help message and exit

.TP
.BI -c|--clone " "TYPE
clone installation configuration file into user folder (SCRIPTS, THEMES, EVENTS)

.TP
.BI -e|--edit " "TYPE
edit user conf file (SCRIPTS, THEMES, EVENTS)
