.TH NAIVECALENDAR 1 "January 6, 2021"

.SH NAME
naivecalendar-add-event
- Add, modify, delete an event entry


.SH SYNOPSIS
.B naivecalendar-add-event [-h] [-o] [-n|-d
.I EVENT_NAME
.B ] [-v 
.I NEW_VALUE
.B ] 

.SH DESCRIPTION
.B naivecalendar-add-event
is a bash script to create, override, delete events definition in ~/.config/naivecalendar/global/events.cfg

.SH OPTIONS

.TP
.B -h|--help 
show this help message and exit

.TP
.BI -n|--new " "NEW_EVENT
name of the new event

.TP
.BI -v|--value " "NEW_VALUE
string value of the new event (see any config file for format spec)

.TP
.B -o|--override         
override value if event already exist

.TP
.B -d|--delete             
delete event

