.TH NAIVECALENDAR 1 "January 6, 2021"

.SH NAME
naivecalendar-add-event
- Add, modify, delete an event entry in all user themes


.SH SYNOPSIS
.B naivecalendar-add-event [-h] [-o] [-n|-d
.I EVENT_NAME
.B ] [-v 
.I NEW_VALUE
.B ] 

.SH DESCRIPTION
.B naivecalendar-add-event
is a bash script to create, override, delete an event definition for all naivecalendar themes in ~/.config/naivecalendar.themes at once

/!\\ If one file already get this event, nothing will be set, to force for all use -o|--override flag

/!\\ Save your themes before use!

.SH OPTIONS

.TP
.B -h|--help 
show this help message and exit

.TP
.BI -n|--new " "NEW_EVENT
name of the new event

.TP
.BI -v|--value " "NEW_VALUE
string value of the new event (see any config file for format spec)

.TP
.B -o|--override         
override value if event already exist

.TP
.B -d|--delete             
delete event from all themes files

